3

diff --git a/.github/workflows/monorepo.yml b/.github/workflows/monorepo.yml
--- a/.github/workflows/monorepo.yml
+++ b/.github/workflows/monorepo.yml
@@ -58,7 +58,7 @@ jobs:
       - name: Check results
         run: |
           if [ "${{ needs.build.result }}" == "failure" ]; then
-          echo "::error::Some builds failed!"
-          exit 1
-        fi
-        echo "All builds succeeded!"
+            echo "::error::Some builds failed!"
+            exit 1
+          fi
+          echo "All builds succeeded!"
